//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_photos
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Order_Number { get; set; }
        public Nullable<int> Photograph_Id { get; set; }
        public Nullable<int> PriceInfo_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public string Credit_No { get; set; }
    }
}
