//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_photos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Info
    {
        public int id { get; set; }
        public string Size { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Sale_Price { get; set; }
    }
}
