//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_photos
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public Nullable<int> User_Type { get; set; }
        public string User_Profile { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Order_id { get; set; }
        public string Credit_Card { get; set; }
    }
}
